version: '3.8'

services:
  api:
    build: .
    depends_on:
      - postgres
    profiles:
      - with-main-service

  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: "sells"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"

volumes:
  postgres-data:
  pgadmin:
